### ISSUE TITLE
Ensure birth date input supports autocomplete

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/ballotbuddies#61]
Context: https://citizenlabs.slack.com/archives/C02HD9MJ7DM/p1634951988006900

**Comment by joel6653** [comment]
Autocomplete works in Safari, but not in Chrome (desktop). I let autocomplete enter the date in m/d/yyyy format, and it was recognized just fine. (It also worked as per the suggested format.)  I'm not sure how to get autocomplete to work in Chrome (desktop). Will check out on a mobile device in both browsers.

**Comment by joel6653** [comment]
On Chrome (desktop), autocomplete works only with passwords, payment methods, and addresses. Birthdate is not one of the fields it will remember.

**Comment by jacebrowning** [comment]
@joel6653 Thanks for checking that!

I guess we can close this since the app is setting the right inputs and we're at the limitation of browser support.
